Dont use PARTITIONED join with at most scalar build side
starburstdata/facebook-presto pull request #17
Opened 2018-02-21 20:24 UTC by kokosing

Dont use PARTITIONED join with at most scalar build side

2018-02-27 14:00 UTC, findepi commented
How this relates to https://github.com/starburstdata/presto/pull/16?

2018-02-28 10:32 UTC, kokosing commented
> How this relates to #16?
It is just another change. However I believe there are some code conflicts.

2018-03-06 09:33 UTC, findepi requested changes
Please turn this into `!fixup Add ReorderJoins rule to pick the best join order` and point at epic 16.

2018-03-06 09:33 UTC, findepi commented on presto-main/src/main/java/com/facebook/presto/sql/planner/iterative/rule/ReorderJoins.java
> +                    possibleJoinNodes.add(new JoinEnumerationResult(costProvider.getCumulativeCost(node), Optional.of(node)));
I think this is not correct. I think that when the `getJoinDistributionType(session) == PARTITIONED` and we join `A` with `B` and `B` is scalar, we should generate broadcast join `A-B`. However, I think we will generate repartitioned join `B-A`.

2018-03-07 13:02 UTC, kokosing commented
Superseded by: https://github.com/starburstdata/presto/pull/27

2018-03-07 13:02 UTC, closed without merging