[WIP] Distributed merge sort
starburstdata/facebook-presto pull request #7
Opened 2018-01-02 16:39 UTC by sopel39

Internal review, supersedes:  https://github.com/prestodb/presto/pull/8169

2018-01-05 16:55 UTC, sopel39 commented on presto-main/src/main/java/com/facebook/presto/sql/planner/LocalExecutionPlanner.java
> +            if (node.getOrderingScheme().isPresent()) {
I don't think there should be a local exchange when ordering schema is present. Such local exchange breaks ordering so planner shouldn't add it.

Otherwise we need to reorder data again with local merge at the top of stage (this is redundant). Computation parallelism of sorted data can probably be addressed in a better way (e.g: merge sort operator only after compute intensive operations are parallized in the plan), but currently there is a gathering distributed sort operator which is hard to avoid in current codebase.

2018-01-05 16:56 UTC, sopel39 commented on presto-main/src/main/java/com/facebook/presto/operator/exchange/LocalExchangePageSupplier.java
> +/*
I am not sure we need local exchanges at all. We need to revisit this commit. I would rather avoid it since it adds additional non-trivial complexity.

2018-01-18 16:26 UTC, sopel39 commented on presto-main/src/main/java/com/facebook/presto/operator/MergeSortProcessor.java
> +    public PageWithPosition poll()
this is `O(N)`

2018-01-18 16:26 UTC, sopel39 commented on presto-main/src/main/java/com/facebook/presto/operator/MergeSortProcessor.java
> +import java.util.ArrayList;
squash with `MergeSortProcessor` commit

2018-01-18 16:26 UTC, sopel39 commented on presto-main/src/main/java/com/facebook/presto/operator/MergeSortProcessor.java
> +        if (mergeSources.stream().allMatch(source -> source.isBlocked().isDone())) {
Get blocked futures just once, instead of here and below.

2018-01-18 16:26 UTC, sopel39 commented on presto-main/src/main/java/com/facebook/presto/operator/MergeSortProcessor.java
> +            blocked = pageSupplier.isBlocked();
inline

2018-01-18 16:26 UTC, sopel39 commented on presto-main/src/main/java/com/facebook/presto/operator/MergeSortProcessor.java
> +            if (currentPage != null && !currentPage.isFinished()) {
extract to `isCurrentPageFinished`.

2018-01-18 16:26 UTC, sopel39 commented on presto-main/src/main/java/com/facebook/presto/operator/MergeSortProcessor.java
> +            if (blocked != null && !blocked.isDone()) {
this should go below `if (currentPage != null && !currentPage.isFinished()) {`

2018-01-18 16:26 UTC, sopel39 commented on presto-main/src/main/java/com/facebook/presto/operator/MergeSortProcessor.java
> +            if (blocked == null) {
this should rather be check state: `must check isBlocked before pooling page`

2018-01-18 16:26 UTC, sopel39 commented on presto-main/src/main/java/com/facebook/presto/operator/MergeSortProcessor.java
> +        public void incrementPosition()
test only/package private?

edit: no longer needed.

2018-01-18 16:26 UTC, sopel39 commented on presto-main/src/test/java/com/facebook/presto/operator/TestMergeSortProcessor.java
> +        int rowsCount = sortedPages.stream().flatMap(List::stream).mapToInt(Page::getPositionCount).sum();
break line

2018-01-18 16:26 UTC, sopel39 commented on presto-main/src/test/java/com/facebook/presto/operator/TestMergeSortProcessor.java
> +            processor.isBlocked().get();
assert is done

2018-01-18 16:26 UTC, sopel39 commented on presto-main/src/test/java/com/facebook/presto/operator/TestMergeSortProcessor.java
> +            pageBuilder.declarePosition();
use `pageWithPosition.appendTo`

2018-01-18 16:26 UTC, sopel39 commented on presto-main/src/main/java/com/facebook/presto/operator/MergeOperator.java
> +    private static final class UpdateSystemMemory
rebase no longer needed

2018-01-18 16:26 UTC, sopel39 commented on presto-main/src/main/java/com/facebook/presto/operator/MergeOperator.java
> +        return closed || (mergeSortProcessor != null && mergeSortProcessor.isFinished() && pageBuilder.isEmpty());
this should rather be `closed && (mergeSortProcessor == null || mergeSortProcessor.isFinished()) && pageBuilder.isEmpty()`

2018-01-18 16:26 UTC, sopel39 commented on presto-main/src/main/java/com/facebook/presto/operator/MergeOperator.java
> +        if (closed) {
technically this is not correct (but probably works in current codebase), there might be partially merged pages still.

2018-01-18 16:26 UTC, sopel39 commented on presto-main/src/main/java/com/facebook/presto/operator/MergeOperator.java
> +        closer.register(mergeSortProcessor);
merger shouldn't be registered with closer. It should be closed in `isFinished()` when no more pages would be produced, see: `com.facebook.presto.operator.FilterAndProjectOperator#isFinished`

2018-01-18 16:26 UTC, sopel39 commented on presto-main/src/main/java/com/facebook/presto/operator/MergeOperator.java
> +    private boolean closed;
this is probably not needed

2018-01-18 16:26 UTC, sopel39 commented on presto-main/src/main/java/com/facebook/presto/operator/MergeOperator.java
> +        try {
I would rather this call `finish`. I think it can also close `mergeSortProcessor` and set it to null

2018-01-18 16:26 UTC, sopel39 commented on presto-main/src/main/java/com/facebook/presto/operator/MergeOperator.java
> +            pageBuilderLocalMemoryContext.setBytes(pageBuilder.getRetainedSizeInBytes());
remove TODO from `Implement MergeSortProcessor `

2018-01-18 16:26 UTC, sopel39 commented on presto-main/src/main/java/com/facebook/presto/operator/MergeOperator.java
> +        if (pageBuilder.isEmpty()) {
inline or remove this condition

2018-01-18 16:26 UTC, sopel39 commented on presto-main/src/main/java/com/facebook/presto/operator/MergeOperator.java
> +            pageBuilder.reset();
update memory usage.

2018-01-18 16:26 UTC, sopel39 commented on presto-main/src/main/java/com/facebook/presto/sql/planner/OrderingScheme.java
> +        this.orderings = ImmutableMap.copyOf(orderings);
add check state that key set equals orderBy symbols set

2018-01-18 16:26 UTC, sopel39 commented on presto-main/src/main/java/com/facebook/presto/sql/planner/optimizations/StreamPropertyDerivations.java
> +                case GATHER: {
brackets not needed

2018-01-18 16:26 UTC, sopel39 commented on presto-main/src/main/java/com/facebook/presto/sql/planner/iterative/rule/PushProjectionThroughExchange.java
> +            if (exchange.getPartitioningScheme().getHashColumn().isPresent()) {
should be part of commit that introduces ordering scheme

2018-01-18 16:26 UTC, sopel39 commented on presto-main/src/main/java/com/facebook/presto/sql/planner/iterative/rule/PushProjectionThroughExchange.java
> +            List<Symbol> inputs = new ArrayList<>();
not needed

2018-01-18 16:26 UTC, sopel39 commented on presto-main/src/main/java/com/facebook/presto/sql/planner/iterative/rule/PushProjectionThroughExchange.java
> +            // Need to deduplicate inputs in case partitioning/hash/ordering columns overlap
this seems should be handled by unalias symbol references

2018-01-18 16:26 UTC, sopel39 commented on presto-main/src/main/java/com/facebook/presto/sql/planner/optimizations/AddExchanges.java
> -                                        roundRobinExchange(
original planner commit shouldn't have this RR exchange

2018-01-18 16:26 UTC, sopel39 commented on presto-tests/src/main/java/com/facebook/presto/tests/RegexMethodSelector.java
> +/*
this is hacky, just extract sort test to separate tests class (those are engine tests not connector)

2018-01-23 13:53 UTC, kokosing reviewed
some initial comments, will get back to it tomorrow

2018-01-23 13:53 UTC, kokosing commented on presto-memory-context/src/main/java/com/facebook/presto/memory/context/MemoryTrackingContext.java
> + * <p>
unrelated, undo

2018-01-23 13:53 UTC, kokosing commented on presto-main/src/main/java/com/facebook/presto/operator/DriverYieldSignal.java
> + * <pre> {@code
extract to separate commit such changes

2018-01-23 13:53 UTC, kokosing commented on presto-main/src/main/java/com/facebook/presto/operator/ContinuousWork.java
> +     * @return boolean to indicate if result is ready or the continuous work has finished.
> or the continuous work has finished.

I would remove this

2018-01-23 13:53 UTC, kokosing commented on presto-main/src/main/java/com/facebook/presto/operator/ContinuousWork.java
> +     * @return true if a work is blocked.
remove such not much telling comment

2018-01-23 13:53 UTC, kokosing commented on presto-main/src/main/java/com/facebook/presto/operator/ContinuousWork.java
> +     * Execute unit of work.
> Execute unit of work.

process()... so it executes... the comment is not needed.

2018-01-23 13:53 UTC, kokosing commented on presto-main/src/main/java/com/facebook/presto/operator/ContinuousWork.java
> +    T getResult();
Can I call this method once or multiple times per call of `process` method?

2018-01-23 13:53 UTC, kokosing commented on presto-main/src/main/java/com/facebook/presto/util/ContinuousWorkUtils.java
> +        PriorityQueue<ElementAndWork<T>> queue = new PriorityQueue<>(2,
put 2 in the next line

2018-01-23 13:53 UTC, kokosing commented on presto-main/src/main/java/com/facebook/presto/operator/ContinuousWork.java
> +public interface ContinuousWork<T>
maybe we could call it a `Process`

2018-01-23 13:53 UTC, kokosing commented on presto-main/src/main/java/com/facebook/presto/util/ContinuousWorkUtils.java
> +    public static <T> ContinuousWork<T> mergeSorted(Iterable<ContinuousWork<T>> workIterable, Comparator<T> comparator)
I would explicitly name it `SortedContinuesWork`

2018-01-23 13:53 UTC, kokosing commented on presto-main/src/main/java/com/facebook/presto/util/ContinuousWorkUtils.java
> +    public static <T, R> ContinuousWork<R> transform(ContinuousWork<T> work, Function<T, R> transformation)
s/transform/map?

2018-01-23 13:53 UTC, kokosing commented on presto-main/src/main/java/com/facebook/presto/util/ContinuousWorkUtils.java
> +        final T element;
private

2018-01-23 13:53 UTC, kokosing commented on presto-main/src/main/java/com/facebook/presto/util/ContinuousWorkUtils.java
> +        ElementAndWork(T element, ContinuousWork<T> work)
private

2018-01-23 13:53 UTC, kokosing commented on presto-main/src/main/java/com/facebook/presto/util/ContinuousWorkUtils.java
> +        final ResultType type;
make them private

2018-01-23 13:53 UTC, kokosing commented on presto-main/src/main/java/com/facebook/presto/util/ContinuousWorkUtils.java
> +    public static class State<T>
add `@Immutable` and final

2018-01-23 13:53 UTC, kokosing commented on presto-main/src/main/java/com/facebook/presto/util/ContinuousWorkUtils.java
> +        enum ResultType
public

2018-01-23 13:53 UTC, kokosing commented on presto-main/src/main/java/com/facebook/presto/util/ContinuousWorkUtils.java
> +                state = supplier.get();
check if state is null

2018-01-23 13:53 UTC, kokosing commented on presto-main/src/main/java/com/facebook/presto/util/ContinuousWorkUtils.java
> +    public static <T> ContinuousWork<T> createFrom(Supplier<State<T>> supplier)
remove `From`

2018-01-24 10:42 UTC, sopel39 commented on presto-main/src/main/java/com/facebook/presto/util/ContinuousWorkUtils.java
> +        ElementAndWork(T element, ContinuousWork<T> work)
I think we had this discussion some time before. Somebody mentioned (@findepi ?) that using access modifiers in private classes doesn't make much sense since they are visible from nesting class anyway. Therefore we can just make nested class methods and fields package private. I think it makes sense (code is shorter too).

2018-01-24 10:43 UTC, sopel39 commented on presto-main/src/main/java/com/facebook/presto/util/ContinuousWorkUtils.java
> +        enum ResultType
no need to expose this

2018-01-24 10:49 UTC, sopel39 commented on presto-main/src/main/java/com/facebook/presto/util/ContinuousWorkUtils.java
> +                state = supplier.get();
`requireNotNull`

2018-01-24 10:53 UTC, sopel39 commented on presto-main/src/main/java/com/facebook/presto/util/ContinuousWorkUtils.java
> +    public static <T> ContinuousWork<T> mergeSorted(Iterable<ContinuousWork<T>> workIterable, Comparator<T> comparator)
It's named after: https://google.github.io/guava/releases/15.0/api/docs/src-html/com/google/common/collect/Iterators.html#line.1244

2018-01-24 11:03 UTC, sopel39 commented on presto-main/src/main/java/com/facebook/presto/operator/ContinuousWork.java
> +    T getResult();
Can be called multiple times

2018-01-24 11:09 UTC, sopel39 commented on presto-main/src/main/java/com/facebook/presto/operator/ContinuousWork.java
> +     * @return boolean to indicate if result is ready or the continuous work has finished.
I think it's part of contract so I would rather leave it.

2018-01-24 11:15 UTC, sopel39 commented on presto-main/src/main/java/com/facebook/presto/operator/ContinuousWork.java
> +public interface ContinuousWork<T>
I have updated comment for this method. For reference see also: `com.facebook.presto.operator.Work#process`

2018-01-26 20:07 UTC, kokosing requested changes
I finished the first pass. I need to revisit planner changes some time later. 

Maybe we could try to start merging this to master, if you find some trivial commits which could be extracted that might be good start.

2018-01-26 20:07 UTC, kokosing commented on presto-main/src/main/java/com/facebook/presto/operator/DriverYieldSignal.java
> +    public synchronized void resetYieldForTesting()
I have always a problem with such commits. IMO when introduced thing is simple it should be squashed with the its usage, if it is complicated it should be extracted too keep reviewer focus.

2018-01-26 20:07 UTC, kokosing commented on presto-main/src/main/java/com/facebook/presto/util/ContinuousWorkUtils.java
> +    public static <T> ContinuousWork<T> mergeSorted(Iterable<ContinuousWork<T>> workIterable, Comparator<T> comparator)
`SortedCountiunes` could contain comparator in it, so that way you will be sure that they are sorted in the same way and you could change API to:
```
public static <T> SortedContinuousWork<T> merge(Iterable<SortedContinuousWork<T>> workIterable)
```

2018-01-26 20:07 UTC, kokosing commented on presto-main/src/main/java/com/facebook/presto/util/ContinuousWorkUtils.java
> +    {
check if arguments are not null

2018-01-26 20:07 UTC, kokosing commented on presto-main/src/main/java/com/facebook/presto/util/ContinuousWorkUtils.java
> +                (firstElement, secondElement) -> comparator.compare(firstElement.element, secondElement.element));
you could use `Comparator::comparing` here: `comparing(ElementAndWork::element)`

2018-01-26 20:07 UTC, kokosing commented on presto-main/src/main/java/com/facebook/presto/util/ContinuousWorkUtils.java
> +    public static <T> ContinuousWork<T> flatten(ContinuousWork<Iterator<T>> work)
`flatMap`?

2018-01-26 20:07 UTC, kokosing commented on presto-main/src/main/java/com/facebook/presto/util/ContinuousWorkUtils.java
> +    public static <T, R> ContinuousWork<R> compose(ContinuousWork<T> work, Function<Optional<T>, State<R>> composition)
to me it is rather `transform`. You transform one to the other. Compose would mean that you have several work instances and you compose one.

2018-01-26 20:07 UTC, kokosing commented on presto-main/src/main/java/com/facebook/presto/util/ContinuousWorkUtils.java
> +                    State<R> state = requireNonNull(composition.apply(element));
add a message

2018-01-26 20:07 UTC, kokosing commented on presto-main/src/main/java/com/facebook/presto/util/ContinuousWorkUtils.java
> +                    return State.ofResult(elementAndWork.element);
it could be last result, but you still set `needsMoreData`

2018-01-26 20:07 UTC, kokosing commented on presto-main/src/main/java/com/facebook/presto/operator/ContinuousWork.java
> +public interface ContinuousWork<T>
should not be this `Closeable`

2018-01-26 20:07 UTC, kokosing commented on presto-main/src/main/java/com/facebook/presto/util/ContinuousWorkUtils.java
> +    public static <T, R> ContinuousWork<R> compose(ContinuousWork<T> work, Function<Optional<T>, State<R>> composition)
I am not sure if `composition` should return `State`. Think of:
`Function<Optional<T>, Optional<R>>`. `Optional.<T>empty()` means no data (work finished). `Optional.<R>empty()` no output (aka needs more data). Then you would not need the `State.NEEDS_MORE_DATA`, which is a bit hacky as it do not match `ContinuesWork` states. That way it would be much simplier.

In current shape, composition may return `State.blocked()` or `State.finished()`, which will overwrite work output, is it desired? It looks useful, but I am not sure if you take advantage of it today. 
I would not use `State` here as it is related with `ContinuesWork`, but something different related only to this method. 

Another idea came to my mind:

I think this method could be named `flatMap` and have API like:
```
public static <T, R> ContinuousWork<R> flatMap(ContinuousWork<T> work, Function<Optional<T>, Optional<Stream<R>>> composition)
```

 - `Stream` might be replaced with `Iterator` or `Iterable`, up to you.
 - `Optional<Stream<R>>> .empty()` means element was not consumed

And the best idea, what if you introduce something like `ContinuesWorkOperator`?

```
    interface ContinuesWorkOperaror<T, R>
    {
        boolean isBlocked();

        /**
         * @return a blocked future when {@link ContinuousWork#isBlocked()} returned true.
         */
        ListenableFuture<?> getBlockedFuture();

        /**
         * @return true if the continuous work is finished. No more results are expected.
         */
        boolean isFinished();

        Stream<R> process(T t);
    }
```

2018-01-26 20:07 UTC, kokosing commented on presto-main/src/main/java/com/facebook/presto/util/ContinuousWorkUtils.java
> +    public static final class State<T>
rename it to `ContinuesWorkState`

2018-01-26 20:07 UTC, kokosing commented on presto-main/src/main/java/com/facebook/presto/util/ContinuousWorkUtils.java
> +        final boolean needsMoreData;
this is wrong name, it suggests that work require some input like `com.facebook.presto.operator.Operator#addInput`. In general you need to call `work.process()` anyway until it get finished. I would prefer to remove it.

2018-01-26 20:07 UTC, kokosing commented on presto-main/src/test/java/com/facebook/presto/util/TestContinuousWorkUtils.java
> +    @Test
you are using futures here, so maybe you could add timeout to test just in case

2018-01-26 20:07 UTC, kokosing commented on presto-main/src/test/java/com/facebook/presto/util/TestContinuousWorkUtils.java
> +        SettableFuture<?> firstFuture = SettableFuture.create();
add also a test with two streams which contain only `State.finished()`

2018-01-26 20:07 UTC, kokosing commented on presto-main/src/test/java/com/facebook/presto/util/TestContinuousWorkUtils.java
> +                ContinuousWorkUtils.map(
in tests of `flatten` you are using `map`. Both of them are using `compose`, in case of bug it might be possible to get false positive. Maybe simply provide these iterators.

2018-01-26 20:07 UTC, kokosing commented on presto-main/src/main/java/com/facebook/presto/operator/PageComparator.java
> +public interface PageComparator
It does sort `pages` ie. collection of pages, but rows in pages. Maybe we could call `PagePositionComparator`?

2018-01-26 20:07 UTC, kokosing commented on presto-main/src/main/java/com/facebook/presto/operator/SimplePageComparator.java
> +    {
Do not need you check:
 - if pages `left` and `right`, have the same number of columns, have the same types
 - pages have all the channels required by `sortChannels`

Checking that every call of `compareTo` would be a performance hit, so maybe you would need to have:
```
public interface PageCompartorFactory
{
    PageComparator create(Page left, Page right);
}

public interface PageComparator
{
    int compareTo(int leftPosition, int rightPosition);
}
```

2018-01-26 20:07 UTC, kokosing commented on presto-main/src/main/java/com/facebook/presto/operator/ContinuousWork.java
> +{
hey, can you provide methods here like:
```
static <T> ContiunesWork<T> create(Supplier<State<T>> supplier)
{ 
    return ContiunesWorkUtils.create(supplier);
}

<R> ContiunesWork<R> map(Function<T,R> mapper)
{
    return ContiunesWorkUtils.map(this, mapper);
}
...
```
It is much easier to read chained calls than wrapped ones.

2018-01-26 20:07 UTC, kokosing commented on presto-main/src/main/java/com/facebook/presto/util/MergeSortedPages.java
> +    private static class PageWithPosition
It seems to be common case and there is another class like that: `com.facebook.presto.operator.MergeHashSort.PagePosition`. So maybe you could provide public class like that?

2018-01-26 20:07 UTC, kokosing commented on presto-main/src/main/java/com/facebook/presto/util/MergeSortedPages.java
> +                transform(pageProducers, MergeSortedPages::pageWithPositions),
it was a surprise to me that this `transform` came from guava.

2018-01-26 20:07 UTC, kokosing commented on presto-main/src/main/java/com/facebook/presto/util/ContinuousWorkUtils.java
> +                .orElse(State.finished()));
Please fix formatting to: 
```
        return compose(work, elementOptional -> {
            return elementOptional
                    .map(element -> State.ofResult(mapper.apply(element)))
                    .orElse(State.finished());
        });
```
At first I thought you call `.map` on the result of of `compose`

2018-01-26 20:07 UTC, kokosing commented on presto-main/src/main/java/com/facebook/presto/util/MergeSortedPages.java
> +                            return new PageWithPosition(page, position++);
plenty of small objects, is not a cpu waste?

When you compare code like:
```
for (int position = 0; position < page.getPositionCount(); i++ ) {
   ...
}
```
with:
```
ContinuesWork<Page> pages = ...
ContinuesWork<PageWithPosition> pagesWithPosition = map(pages, Utils::toPageWithPosition);
while (true)  {
    if (work.process()) {
        if (!work.isFinished()) {
            PageWithPosition pwp = work.getResult();
            queue.add(new ElementAndWork<>(work.getResult(), work))
        }
    }
   // here you need to handle other states
```

Do you think it matters?

2018-01-26 20:07 UTC, kokosing commented on presto-main/src/main/java/com/facebook/presto/util/MergeSortedPages.java
> +    private static ContinuousWork<Page> buildPage(
it looks like `compact`. It looks very general, not only merge sort specific.

2018-01-26 20:07 UTC, kokosing commented on presto-main/src/main/java/com/facebook/presto/util/MergeSortedPages.java
> +                return State.yield();
it looks like here `pageWithPositionOptional` was just consumed. IMO when `yieldSignal.isSet()` that method should not be called or should be called with something like `State.yield`.

EDIT... now I understand. That is called once again with the same element. It is not much intuitive to me. Using mentioned `ContinuesWorkOperator` would be easier.

2018-01-26 20:07 UTC, kokosing commented on presto-main/src/main/java/com/facebook/presto/util/MergeSortedPages.java
> +            memoryContext.setBytes(pageBuilder.getRetainedSizeInBytes());
it looks like semi squared computation. For each row you calculate page builder size, can you just add a difference, the size of things you have just added to `pageBuilder`?

2018-01-26 20:07 UTC, kokosing commented on presto-main/src/test/java/com/facebook/presto/util/TestMergeSortedPages.java
> +                ImmutableList.of(ASC_NULLS_FIRST, ASC_NULLS_FIRST),
asc and desc?

2018-01-26 20:07 UTC, kokosing commented on presto-main/src/main/java/com/facebook/presto/util/ContinuousWorkUtils.java
> +        enum ResultType
I would rename it to just `Type`

2018-01-26 20:07 UTC, kokosing commented on presto-main/src/main/java/com/facebook/presto/util/ContinuousWorkUtils.java
> +                        element = Optional.empty();
I would change it to:
```
if (state.isNotOneOf(BLOCKED, YIELD)) 
{
    element = Optional.empty();
}
```
It took me a while to understand the idea here.

2018-01-26 20:07 UTC, kokosing commented on presto-main/src/test/java/com/facebook/presto/operator/TestingExchangeHttpClientHandler.java
> +public class TestingExchangeHttpClientHandler
is this only `Exchange` related?

2018-01-26 20:07 UTC, kokosing commented on presto-main/src/test/java/com/facebook/presto/operator/TestingExchangeHttpClientHandler.java
> +        this.taskBuffers = taskBuffers;
rnn

2018-01-26 20:07 UTC, kokosing commented on presto-main/src/main/java/com/facebook/presto/operator/MergeOperator.java
> +            return outputChannels.stream()
you can use `MoreLists.mappedCopy` here

2018-01-26 20:07 UTC, kokosing commented on presto-main/src/main/java/com/facebook/presto/operator/MergeOperator.java
> +            return ContinuousWorkUtils.State.ofResult(client.pollPage());
maybe you should put this method to `ExchangeClient`, then here you would just:
```
return ContinuesWorkUtils.map(client.pages(), serde::deserialize);
```

2018-01-26 20:07 UTC, kokosing commented on presto-main/src/main/java/com/facebook/presto/operator/MergeOperator.java
> +    private static ContinuousWork<Page> createPageProducerFor(ExchangeClient client, PagesSerde serde)
It is no longer page producer. Also please remove `For`

2018-01-26 20:07 UTC, kokosing commented on presto-main/src/main/java/com/facebook/presto/operator/MergeOperator.java
> +    private ContinuousWork<Page> mergedPages;
Maybe you could provide an abstraction of `Operator` wrapping `ContinuesWork<Page>`?

2018-01-26 20:07 UTC, kokosing commented on presto-main/src/main/java/com/facebook/presto/operator/MergeOperator.java
> +        if (mergedPages.isBlocked()) {
it could be `null`. Neither `noMoreSplits` or `SettableFuture.set` are synchronized or `mergedPages` is volatile.

2018-01-26 20:07 UTC, kokosing commented on presto-main/src/main/java/com/facebook/presto/operator/MergeOperator.java
> +        checkState(mergedPages != null, "mergeSources must be non-null when getting output");
why not to return null? Otherwise I would say that `noMoreSplits` is required to be called first.

2018-01-26 20:07 UTC, kokosing commented on presto-main/src/test/java/com/facebook/presto/operator/OperatorAssertion.java
> +    private static final Duration UNBLOCKED_DEFAULT_TIMEOUT = new Duration(1, SECONDS);
remove it

2018-01-26 20:07 UTC, kokosing commented on presto-main/src/test/java/com/facebook/presto/operator/OperatorAssertion.java
> +        if (!waitForOperatorToUnblock(operator, timeout)) {
IMO it is wrong, it should be something like:

```
return operator.isBlocked().get(0, TimeUnit.MILLISECONDS);
```
or
```
return operator.isBlocked().isDone();
```

2018-01-26 20:07 UTC, kokosing commented on presto-main/src/test/java/com/facebook/presto/operator/OperatorAssertion.java
> +    private static final Duration BLOCKED_DEFAULT_TIMEOUT = new Duration(10, MILLISECONDS);
remove it, it is very test specific

2018-01-26 20:07 UTC, kokosing commented on presto-main/src/test/java/com/facebook/presto/operator/TestMergeOperator.java
> +        exchangeClientSupplier = null;
use `Closer` here

2018-01-26 20:07 UTC, kokosing commented on presto-main/src/test/java/com/facebook/presto/operator/TestMergeOperator.java
> +        assertOperatorIsUnblocked(operator);
it should be blocked as task 2 did not get any data yet.

2018-01-26 20:07 UTC, kokosing commented on presto-main/src/main/java/com/facebook/presto/sql/planner/plan/ExchangeNode.java
> +        checkArgument(type == Type.GATHER || !orderingScheme.isPresent(), "ordering scheme can be set only for GATHERING");
put it below into `orderingSchema.ifPresent(...`

2018-01-26 20:07 UTC, kokosing commented on presto-main/src/main/java/com/facebook/presto/sql/planner/iterative/rule/PushPartialAggregationThroughExchange.java
> +                Optional.empty());
I think you are missing `node.getOrderingScheme()` here

2018-01-26 20:07 UTC, kokosing commented on presto-main/src/main/java/com/facebook/presto/sql/planner/iterative/rule/PushProjectionThroughExchange.java
> +            if (exchange.getOrderingScheme().isPresent()) {
I think for now we could `return Result.empty()` here and in other rules, and the we could support `OrderingScheme` in rules one by one with proper testing

2018-01-26 20:07 UTC, kokosing commented on presto-main/src/main/java/com/facebook/presto/sql/planner/optimizations/AddLocalExchanges.java
> +                        any().withOrderSensitivity());
I would divide this commit into two. One add just add ordering to exchange node without any support for this, and then add support ordering for other things like support for ordering in property derivation etc (maybe that could be even divided further).

2018-01-26 20:07 UTC, kokosing commented on presto-main/src/main/java/com/facebook/presto/sql/planner/optimizations/PropertyDerivations.java
>                  case REPARTITION:
add check state that there is no ordering here

2018-01-26 20:07 UTC, kokosing commented on presto-main/src/main/java/com/facebook/presto/SystemSessionProperties.java
> +                booleanSessionProperty(
adding feature flag changes could be extracted to separate commit

2018-01-26 20:07 UTC, kokosing commented on presto-main/src/main/java/com/facebook/presto/sql/planner/LocalExecutionPlanner.java
> +                return createMergeSource(node, context);
put ordering here as parameter

2018-01-26 20:07 UTC, kokosing commented on presto-main/src/main/java/com/facebook/presto/sql/planner/optimizations/AddExchanges.java
> +            if (isDistributedSortEnabled(session)) {
else if?

2018-01-26 20:07 UTC, kokosing commented on presto-tests/src/test/java/com/facebook/presto/tests/TestDistributedSortQueries.java
> +public class TestDistributedSortQueries
it is a pity that we will run non sort related tests here

2018-01-26 20:07 UTC, kokosing commented on presto-main/src/main/java/com/facebook/presto/operator/exchange/LocalMergeExchange.java
> +        @GuardedBy("lock")
why not guarded by `this`?

2018-01-26 20:07 UTC, kokosing commented on presto-main/src/main/java/com/facebook/presto/operator/exchange/LocalMergeExchange.java
> +            synchronized (lock) {
add `checkState(!writeFinished)`

2018-01-26 20:07 UTC, kokosing commented on presto-main/src/main/java/com/facebook/presto/operator/exchange/LocalMergeExchange.java
> +        public void enqueuePage(Page page)
rename it to `writePage` to make it consistent with `isWriteBlocked`

2018-01-26 20:07 UTC, kokosing commented on presto-main/src/main/java/com/facebook/presto/operator/exchange/LocalMergeExchange.java
> +                    return;
it looks like an invalid state. If we are unable to write pages we should inform producers to stop as well (propagate)

2018-01-26 20:07 UTC, kokosing commented on presto-main/src/main/java/com/facebook/presto/operator/exchange/LocalMergeExchange.java
> +        public Page poolPage()
`readPage`?

2018-01-26 20:07 UTC, kokosing commented on presto-main/src/main/java/com/facebook/presto/operator/exchange/LocalMergeExchange.java
> +                readBlocked.set(null);
this will unblock readers who will try to read pages. Reading pages will `readBlocked = SettableFuture.create();`

2018-01-26 20:07 UTC, kokosing commented on presto-main/src/main/java/com/facebook/presto/operator/exchange/LocalMergeSinkOperator.java
> +            throws Exception
no exception is thrown here

2018-01-26 20:07 UTC, kokosing commented on presto-main/src/main/java/com/facebook/presto/operator/exchange/LocalMergeSourceOperator.java
> +                .map(LocalMergeSourceOperator::createPageProducerFor)
I think `LocalMergeSourceOperator` should have a method like:
```
ContinuousWork<Page> pages()
```
I believe it should simplify its implementation

2018-01-26 20:07 UTC, kokosing commented on presto-main/src/main/java/com/facebook/presto/operator/exchange/LocalMergeExchange.java
> +        public void enqueuePage(Page page)
I think instead of this it should expose something like:
```
Consumer<ContinuesWork<Page>> getPageConsumer();
```

2018-01-26 20:07 UTC, kokosing commented on presto-main/src/main/java/com/facebook/presto/sql/planner/LocalExecutionPlanner.java
> +                return createLocalMerge(node, context);
pass ordering scheme as paratemeter

2018-01-26 20:07 UTC, kokosing commented on presto-main/src/main/java/com/facebook/presto/operator/exchange/LocalMergeExchange.java
> +public class LocalMergeExchange
I do not see anything `Merge` related here, maybe we should modify `com.facebook.presto.operator.exchange.LocalExchange` to support `ContinuesWork<Page>` as supplier and consumer of pages?

2018-01-26 20:07 UTC, kokosing commented on presto-main/src/main/java/com/facebook/presto/sql/planner/optimizations/AddLocalExchanges.java
> +            if (SystemSessionProperties.isDistributedSortEnabled(session)) {
it would be nice to have planner changes in separate commit

2018-01-26 20:07 UTC, kokosing commented on presto-main/src/main/java/com/facebook/presto/sql/planner/optimizations/AddLocalExchanges.java
> +                PlanWithProperties source = node.getSource().accept(this, any());
sourceWithProperties?

2018-01-26 20:07 UTC, kokosing commented on presto-main/src/main/java/com/facebook/presto/sql/planner/optimizations/AddLocalExchanges.java
> +                Map<Symbol, SortOrder> orderings = node.getOrderings();
inline these two above

2018-01-26 20:07 UTC, kokosing commented on presto-main/src/main/java/com/facebook/presto/sql/planner/optimizations/AddLocalExchanges.java
> +                        source.getProperties());
add tests for planner where you assert that proper plan is generated

2018-01-26 20:07 UTC, kokosing commented on presto-main/src/main/java/com/facebook/presto/operator/SimplePageComparator.java
> -
in few commits earlier it was introduced, please squash these changes. Do not introduce things which you just remove just a bit later.

2018-01-26 20:07 UTC, kokosing commented on presto-main/src/main/java/com/facebook/presto/sql/gen/OrderingCompiler.java
> +    private static void generatePageIndexCompareTo(ClassDefinition classDefinition, CallSiteBinder callSiteBinder, List<Type> sortTypes, List<Integer> sortChannels, List<SortOrder> sortOrders)
do rename in separate commit

2018-01-26 20:07 UTC, kokosing commented on presto-main/src/main/java/com/facebook/presto/sql/gen/OrderingCompiler.java
> +            log.error(t, "Error compiling merge sort comparator for channels %s with order %s", sortChannels, sortChannels);
we need to make sure when we do some benchmarking (aka scale testing) that there is no such error thrown

2018-01-29 15:16 UTC, sopel39 commented on presto-main/src/main/java/com/facebook/presto/operator/ContinuousWork.java
> +public interface ContinuousWork<T>
not necessarily, there is no use case for that yet.

2018-01-29 15:16 UTC, sopel39 commented on presto-main/src/main/java/com/facebook/presto/operator/MergeOperator.java
> +    private ContinuousWork<Page> mergedPages;
This operator is very specific (it consumes multiple splits). I would leave it for future when we have more use cases of `ContinuesWork<Page>`. There is definitely some future work.

2018-01-29 15:16 UTC, sopel39 commented on presto-main/src/main/java/com/facebook/presto/operator/MergeOperator.java
> +        if (mergedPages.isBlocked()) {
`Operator` instance is used from a single thread.

2018-01-29 15:16 UTC, sopel39 commented on presto-main/src/main/java/com/facebook/presto/operator/MergeOperator.java
> +    private static ContinuousWork<Page> createPageProducerFor(ExchangeClient client, PagesSerde serde)
How would you call it then?

2018-01-29 15:16 UTC, sopel39 commented on presto-main/src/main/java/com/facebook/presto/operator/SimplePageComparator.java
> -
Doesn't compiled `PageComparator` deserve separate commit?

2018-01-29 15:16 UTC, sopel39 commented on presto-main/src/main/java/com/facebook/presto/operator/exchange/LocalMergeExchange.java
> +public class LocalMergeExchange
I actually rewritten then commit so that `LocalMergeExchange` reuses classes around original `LocalExchange`. I think separate `LocalMergeExchange` is required though as it consumes data from multiple `LocalExchangeSources`

> we should modify com.facebook.presto.operator.exchange.LocalExchange to support ContinuesWork<Page> as supplier and consumer of pages?

I am absolutely for that, but let's change the code gradually as `LocalExchange` and surrounding classes are rather complex beasts.

2018-01-29 15:16 UTC, sopel39 commented on presto-main/src/main/java/com/facebook/presto/operator/exchange/LocalMergeExchange.java
> +        @GuardedBy("lock")
This is removed in newer code

2018-01-29 15:16 UTC, sopel39 commented on presto-main/src/main/java/com/facebook/presto/operator/exchange/LocalMergeExchange.java
> +            synchronized (lock) {
ditto

2018-01-29 15:16 UTC, sopel39 commented on presto-main/src/main/java/com/facebook/presto/sql/planner/iterative/rule/PushProjectionThroughExchange.java
> +            if (exchange.getOrderingScheme().isPresent()) {
I think there are tests for it, but in the `planner` commit. I probably need to move it there.

2018-01-29 15:16 UTC, sopel39 commented on presto-main/src/main/java/com/facebook/presto/util/ContinuousWorkUtils.java
> +                    return State.ofResult(elementAndWork.element);
`ofResult(T element)` does that be default, but `needsMore` data is ignored by `ContinuousWorkUtils::create`

2018-01-30 08:47 UTC, sopel39 commented on presto-main/src/main/java/com/facebook/presto/util/ContinuousWorkUtils.java
> +    public static <T> ContinuousWork<T> mergeSorted(Iterable<ContinuousWork<T>> workIterable, Comparator<T> comparator)
What if the data is naturally sorted (like in case of dist sort)? Then you would need to wrap it into `SortedContinuousWork` (with comparator). Also, comparators might not have equals/hashCode method, therefore it might not be possible to verify that all data is sorted in the same way.

2018-01-30 08:47 UTC, sopel39 commented on presto-main/src/main/java/com/facebook/presto/util/ContinuousWorkUtils.java
> +    public static <T> ContinuousWork<T> flatten(ContinuousWork<Iterator<T>> work)
I have added `flatMap` method. `flatten` is now private since it consumes rather strange work: `ContinuousWork<Iterator<T>> work`

The only twist is that we use `Iterator` instead of `Stream`. This is because we need to be able to consume element by element.

2018-01-30 08:47 UTC, sopel39 commented on presto-main/src/main/java/com/facebook/presto/util/ContinuousWorkUtils.java
> +    public static <T, R> ContinuousWork<R> compose(ContinuousWork<T> work, Function<Optional<T>, State<R>> composition)
We need to support few things:
* yielding
* blocking
* returning element
* signaling finished.

I don't see how you can cleanly support yielding when process returns `Stream<R>`. You would have to check `ContinuesWorkOperaror` (for blocked/yielding) each time before obtaining an element. Additionally, `Stream` doesn't allow to consume single element and wait.

Additionally, this interface allows to write continuous work without any intermittent object creation (apart from `ListenableFuture`).

> Function<Optional<T>, Optional<R>>. Optional.<T>empty() means no data (work finished). Optional.<R>empty() no output (aka needs more data)

`Optional.empty` might also mean yielding. 

> In current shape, composition may return State.blocked() or State.finished(), which will overwrite work output, is it desired?

What do you mean by overwriting work output?

> I would not use State here as it is related with ContinuesWork, but something different related only to this method.

I asked @findepi and we decided that there is no need to create redundant objects (they would share most of the states). I have renamed `State` to `WorkState`.

2018-01-30 08:47 UTC, sopel39 commented on presto-main/src/main/java/com/facebook/presto/util/ContinuousWorkUtils.java
> +                        element = Optional.empty();
I will add a comment, The reasoning is: `needsMoreData -> set element to empty to fetch new one`.

2018-01-30 08:47 UTC, sopel39 commented on presto-main/src/main/java/com/facebook/presto/util/ContinuousWorkUtils.java
> +    public static final class State<T>
I have renamed it to just `WorkState`

2018-01-30 08:47 UTC, sopel39 commented on presto-main/src/main/java/com/facebook/presto/util/ContinuousWorkUtils.java
> +        final boolean needsMoreData;
`needsMoreData` is not directly exposed in `ContinuousWork`. `needsMoreData` is needed by `ContinuousWorkUtils#transform` to distinguish if transformation produced a transformed element and wants to consume next source element
OR
it produced a transformed element but still hasn't finished processing the current source element.

For instance this allows you to write transformation that splits `Page` into `PageWithPositions`
OR
transformation that merges `PageWithPositions` into `Page.

2018-01-30 08:47 UTC, sopel39 commented on presto-main/src/main/java/com/facebook/presto/util/ContinuousWorkUtils.java
> +        final T element;
not needed, `ElementAndWork` is private

2018-01-30 08:47 UTC, sopel39 commented on presto-main/src/test/java/com/facebook/presto/util/TestContinuousWorkUtils.java
> +                ContinuousWorkUtils.map(
You would need to wrap them in `ContinuousWork` somehow. I think we can gradually build test cases from assuming simpler methods pass tests.

2018-01-30 11:51 UTC, sopel39 commented on presto-main/src/main/java/com/facebook/presto/operator/SimplePageComparator.java
> +    {
We compare `PageWithPositions`, so you would need to create `PageCompartorFactory` for every pair anyway (no benefit in `PageComparator create(Page left, Page right);`)

2018-01-30 11:51 UTC, sopel39 commented on presto-main/src/main/java/com/facebook/presto/util/MergeSortedPages.java
> +                transform(pageProducers, MergeSortedPages::pageWithPositions),
added explicit `Iterables` reference.

2018-01-30 11:51 UTC, sopel39 commented on presto-main/src/main/java/com/facebook/presto/util/MergeSortedPages.java
> +    private static ContinuousWork<Page> buildPage(
true. It might be exposed when `MergeHashSort` will be ported to `ContinuousWork`. Prefer to leave it private for now.

2018-01-30 11:51 UTC, sopel39 commented on presto-main/src/main/java/com/facebook/presto/util/MergeSortedPages.java
> +                return State.yield();
Yield == call me with the same element so I can continue work.

2018-01-30 11:51 UTC, sopel39 commented on presto-main/src/main/java/com/facebook/presto/util/MergeSortedPages.java
> +            memoryContext.setBytes(pageBuilder.getRetainedSizeInBytes());
True, it's the same as `PageRewriteIterator#next`. Maybe we can decrease update granularity. I will update TODO for now

2018-01-30 11:51 UTC, sopel39 commented on presto-main/src/main/java/com/facebook/presto/util/MergeSortedPages.java
> +                            return new PageWithPosition(page, position++);
I think it might matter. `MergeHashSort` works in the same way. Andrei code was more efficient since his `PageWithPosition` was mutable (you could increment pos) and reused. The same trick can be used here, but I would prefer not to preoptimize.

2018-01-30 11:51 UTC, sopel39 commented on presto-main/src/main/java/com/facebook/presto/util/MergeSortedPages.java
> +    private static class PageWithPosition
that would be next step (if we have time)

2018-01-30 11:51 UTC, sopel39 commented on presto-main/src/test/java/com/facebook/presto/operator/TestingExchangeHttpClientHandler.java
> +public class TestingExchangeHttpClientHandler
yes. Its for testing exchanges only

2018-01-30 11:51 UTC, sopel39 commented on presto-main/src/test/java/com/facebook/presto/operator/TestMergeOperator.java
> +        exchangeClientSupplier = null;
I think `executor.shutdownNow()` shouldn't fail

2018-01-30 11:51 UTC, sopel39 commented on presto-main/src/test/java/com/facebook/presto/operator/TestMergeOperator.java
> +        assertOperatorIsUnblocked(operator);
Not really. In this case blocking future is the one waiting for data from source 1. When this future gets unblocked you have to call `operator.getOutput()` to push computations forward and only then it gets blocked again on source 2.

`ContinuousWorkUtils#mergeSorted` could possibly gather futures from all sources when one future is blocked, but I don't think it give much benefit.

2018-01-30 11:51 UTC, sopel39 commented on presto-main/src/main/java/com/facebook/presto/sql/planner/iterative/rule/PushPartialAggregationThroughExchange.java
> +                Optional.empty());
nope, it compiles

2018-01-30 11:51 UTC, sopel39 commented on presto-main/src/main/java/com/facebook/presto/sql/planner/optimizations/AddLocalExchanges.java
> +                        any().withOrderSensitivity());
I prefer to keep elementary changes in this commit. Unwinding it would take considerable effort and I don't want to spend to much time on it.

2018-01-30 11:51 UTC, sopel39 commented on presto-main/src/main/java/com/facebook/presto/sql/planner/optimizations/PropertyDerivations.java
>                  case REPARTITION:
if anything, it should be checked in `ExchangeNode` constructor

2018-01-30 11:51 UTC, sopel39 commented on presto-main/src/main/java/com/facebook/presto/sql/planner/LocalExecutionPlanner.java
> +                return createMergeSource(node, context);
You need other properties of `RemoteSourceNode` anyway, so I don't think we need to redundantly pass ordering scheme.

2018-01-30 11:51 UTC, sopel39 commented on presto-main/src/main/java/com/facebook/presto/sql/planner/optimizations/AddExchanges.java
> +            if (isDistributedSortEnabled(session)) {
no, because `if (child.getProperties().isSingleNode()) ` doesn't always return (it only returns when natural ordering matches required ordering). Otherwise we might want to do round robin from single node for dist sort.

2018-01-30 11:51 UTC, sopel39 commented on presto-tests/src/test/java/com/facebook/presto/tests/TestDistributedSortQueries.java
> +public class TestDistributedSortQueries
Yup. Not a PR to fix that though (that's continuation of Erics work).

2018-01-30 11:52 UTC, sopel39 commented
applied changes

2018-01-30 13:54 UTC, sopel39 commented
Superseded by: https://github.com/prestodb/presto/pull/9854

2018-01-30 13:54 UTC, closed without merging